<main class="contact_content">         
    <section class="about-contents">
        <div class="informations">
            <div class="about-me">
                <div><h1>ABOUT ME</h1></div>
                <p>PT - Áquila Oliveira, Natural de Salvador-BA, tenho 20 anos, Sou Diretor, Editor e Motion Design e Trabalho na área Audiovisual desde 2014.</p>
                <p class="english">EN - Áquila Oliveira, Born in Salvador-BA, I'm 20 years old, I'm Director, Editor and Motion Design and I've been working in the Audiovisual area since 2014.</p>
            </div>
            <div class="contact">
                <div><h1>CONTACT</h1></div>
                <p>contato@aquilaoliveira.com</p>
                <p class="number">+55 (71) 9 8674-4015</p>
            </div><!--Contact-->
        </div><!--informations-->
        <div class="image">
            <img src="images/FOTO CRACHÁ ÁQUILA .jpg" alt="foto de aquila">
            <div class="redes">
                <ul>
                    <li>
                        <a href="https://www.youtube.com/@aquilaolvr">
                            <img src="images/redes/youtube.png" alt="link youtube">
                        </a>
                    </li>
                    <li>
                        <a href="http://Behance.net/aquilaolvr">
                            <img src="images/redes/behance.png" alt="link behance">
                        </a>
                    </li>
                    <li>
                        <a href="https://www.instagram.com/aquilaolvr/">
                            <img src="images/redes/instagram.png" alt="link instagram">
                        </a>
                    </li>
                    <li>
                        <a href="https://www.linkedin.com/in/%C3%A1quila-oliveira-b5578518a/">
                            <img src="images/redes/linkedin.png" alt="link linkedin" >
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        
    </section>
</main>
