<body class="body">
    <div class="container">
        <div class="overlay"></div>
        <video autoplay muted loop preload>
            <source src="images/videos/DEMOREEL.mp4" type="video/mp4" width="100%" height="50%">
        </video>
        <div class="override">
            <div class="button">
                <a href="/works"><img src="/images/Aquila.png" alt="Logo Aquila Oliveira"></a>
            </div>
        </div>
    </div>
</body>