<main class="main-login">
    <section class="login">
        <form action="/auth" method="post">
            <div>
                <label for="username">Nome de usuário:</label>
                <input type="text" id="username" name="username" required>
            </div>
            <div>
                <label for="password">Senha:</label>
                <input type="password" id="password" name="password" required>
            </div>
            <div>
                <input type="submit" value="Login">
            </div>
        </form>
    </section>
</main>