<main>
    <section class="video-container">
        <div class="titulo">
            <div class="titulo-alinhamento"></div>
            <div class="titulo-alinhamento"><h1>Lorem Ipsum</h1></div>
            <div class="titulo-alinhamento"><a href="/works"><img src="images/menu.png" alt=""></a></div>
            
            
            
        </div>
        <div class="videos">
            <iframe width="80%" height="600" src="https://www.youtube.com/embed/V071UfjmEx4" title="YouTube video player" autoplay frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
        </div>
        <!-- <div class="texto">Lorem ipsum dolor sit amet consectetur adipisicing elit. Debitis maxime, impedit quis modi et quos amet ipsa rerum cupiditate eum rem voluptate nisi harum natus fugit hic aperiam. Hic, ab!</div> -->
    </section>
</main>

