<main>
    <section class="video-container">
        <div class="titulo">
            <div class="titulo-alinhamento"></div>
            <div class="titulo-alinhamento titulo-video"><h1><?=$this->view->videos['titulo']?></h1></div>
            <div class="titulo-alinhamento">
                <a href="/works">
                    <img src="images/icons/circulo-x.svg" alt="fechar página de vídeos">
                </a>
            </div>
        </div>
        <div class="videos">
            <iframe 
                width="70%" 
                height="600" 
                src="https://www.youtube.com/embed/<?=$this->view->videos['link']?>" 
                title="YouTube video player" 
                autoplay 
                frameborder="0" 
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen>
            </iframe>
        </div>
        <!-- <div class="texto">Lorem ipsum dolor sit amet consectetur adipisicing elit. Debitis maxime, impedit quis modi et quos amet ipsa rerum cupiditate eum rem voluptate nisi harum natus fugit hic aperiam. Hic, ab!</div> -->
    </section>
</main>

