<main>
    <div class="button">
        <ul>
            <li><button id="musicVideo" class="active">MUSIC VIDEO</button></li>
            <li><button id="afterMovie">AFTERMOVIE</button></li>
            <li><button id="motionDesign">MOTION DESIGN</button></li>
        </ul>
    </div>
    <section class="album">
        <div class="works">
            <?php  foreach($this->view->videos as $key => $video) { ?> 
                <div class="img-wraper" id="<?=$video['tipo_video']?>">
                    <a href="/video?id=<?=$video['id']?>" class="link" aria-label="<?=$video['titulo']?>">
                        <img src="<?=$video['caminho_thumb']?>" alt="Video <?=$video['id']?>">
                    </a>
                </div>
            <?php } ?>
        </div>
    </section>
</main>


