<header>
    <nav>
        <ul>
            <li><a href="/painel">Publicar Video</a></li>
            <li><a href="/painelVideos">Editar Videos</a></li>
        </ul>
        <img src="images/Aquila.png" alt="logo aquila">
    </nav>
</header>
<main class="main-painel">
    <section class="painel">
        <form action="/salvar?id=<?=$_GET['id']?>" method="post" enctype="multipart/form-data">
            <div>
                <label for="titulo">Titulo:</label>
                <input type="text" id="titulo" name="titulo" required value="<?=$this->view->videos['titulo']?>">
            </div>
            <div>
                <label for="tipoVideo">Tipo de vídeo:</label>
                <select name="tipoVideo" id="tipoVideo">
                    <option value="" disabled selected>Selecione um tipo de vídeo</option>
                    <option value="musicvideo"
                        <?php if ($this->view->videos['tipo_video'] === 'musicvideo') echo 'selected'; ?>>Music Video
                    </option>
                    <option value="aftermovie"
                        <?php if ($this->view->videos['tipo_video'] === 'aftermovie') echo 'selected'; ?>>AfterMovie
                    </option>
                    <option value="motiondesign"
                        <?php if ($this->view->videos['tipo_video'] === 'motiondesign') echo 'selected'; ?>>Motion
                        Design
                    </option>
                </select>
            </div>
            <div>
                <label for="link">Link incorporado:</label>
                <input type="text" id="link" name="link" required value="<?=$this->view->videos['link']?>">
            </div>
            <div>
                <label for="videoThumb">Thumbnail:</label>
                <input type="file" id="videoThumb" name="videoThumb">
            </div>
            <div>
                <input type="submit">
            </div>
        </form>
    </section>
</main>