<html>
<head>
        <meta charset="utf-8" />
		<meta name="description" content="Works and contact - Aquila Oliveira">
		<meta name="author" content="Davi Santana">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="icon" type="image/png" href="images/favicon.png">
		<link rel="stylesheet" href="/css/style_layout1.css">
		<title>Aquila Oliveira</title>
</head>
<body>
    <header class="cabecalho">
        <nav class="cabecalho-navegacao">
            <div class="cabecalho-navegacao-botoes">
                <ul>
                    <li><a href="/" >HOME</a></li>
                    <li><a href="/works">WORK</a></li>
                    <li><a href="/contact">CONTACT</a></li>
                </ul>
            </div>
            <div class="menu-mobile">
                <img src="images/menu.png" alt="" class="menu-img">
            </div>
            <div class="cabecalho-mobile">
                <ul>
                    <li><a href="/" >HOME</a></li>
                    <li><a href="/works">WORK</a></li>
                    <li><a href="/contact">CONTACT</a></li>
                </ul>
            </div>
        </nav>
        <div class="logo"><img src="images/ÁQUILA1.png" alt=""></div>
    </header>
	<?= $this->content() ?>
    <footer>
    
    </footer>
    <script src="js/script.js"></script>
</body>
</html>