<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="UTF-8">
        <meta name="description" content="Works and Contact">
        <meta name="author" content="Davi Santana">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="icon" type="image/png" href="images/favicon.png">
        <meta name="google-site-verification" content="DIe6lVQqebkG0lq-kWiIBzh8e0sxI7J23yp7XLMSV-U" />
        <link rel="stylesheet" href="/css/style_layout1.css">

        <?php if (isset($objeto->exibe_video_youtube) && $this->view->exibe_video_youtube): ?>
            <link rel="preconnect" href="https://www.youtube.com">
        <?php endif; ?>

        <title>Aquila Oliveira</title>
    </head>
<body>
    <header class="cabecalho">
        <nav class="cabecalho-navegacao">
            <div class="cabecalho-navegacao-botoes">
                <ul>
                    <li><a href="/"         >HOME</a></li>
                    <li><a href="/works"    >WORK</a></li>
                    <li><a href="/contact"  >CONTACT</a></li>
                </ul>
            </div>
            <div class="menu-mobile">
                <img src="images/icons/menu-hamburguer.svg" alt="menu" class="menu-img">
            </div>
            <div class="cabecalho-mobile">
                <ul>
                    <li><a href="/"         >HOME</a></li>
                    <li><a href="/works"    >WORK</a></li>
                    <li><a href="/contact"  >CONTACT</a></li>
                </ul>
            </div>
        </nav>
        <div class="logo">
            <img src="images/Aquila.png" alt="logo de Áquila">
        </div>
    </header>
	<?= $this->content() ?>
    <footer>

    </footer>
    <script src="js/script.js"></script>
</body>
</html>