<html>
<head>
        <meta charset="utf-8" />
		<meta name="description" content="Works and contact - Aquila Oliveira">
		<meta name="author" content="Davi Santana">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="stylesheet" href="/css/style_layout2.css">
		<title>Aquila Oliveira</title>
</head>
<body>
	<?= $this->content() ?>
    <script src="js/script.js"></script>
</body>
</html>