<html>
	<head>
	<meta charset="utf-8" />
		<meta name="description" content="Blog da APS">
		<meta name="author" content="Davi Santana">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="stylesheet" href="/css/style_layout.css">
		<link href='https://css.gg/menu-round.css' rel='stylesheet'>
		<title>Aquila Oliveira</title>
	</head>
	<body>
		<?= $this->content() ?>
	</body>
</html>