<!DOCTYPE html>
<html lang="pt-br">
	<head>
		<meta charset="UTF-8">
		<meta name="description" content="Painel - Aquila Oliveira">
		<meta name="author" content="Davi Santana">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="google-site-verification" content="DIe6lVQqebkG0lq-kWiIBzh8e0sxI7J23yp7XLMSV-U" />
		<link rel="stylesheet" href="/css/style_layout2.css">
		<link rel="icon" type="image/png" href="images/favicon.png">
		<title>Aquila Oliveira</title>
	</head>
	<body>
		<?= $this->content() ?>
	</body>
</html>